# Nome do Workflow
name: Deploy to GitHub Pages

# Gatilhos (Triggers): Roda APENAS quando há um push para o branch main
on:
  push:
    branches: [ "main" ]

# Permissões necessárias para que o workflow possa interagir com o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Configuração de concorrência para evitar múltiplas publicações ao mesmo tempo
concurrency:
  group: "pages"
  cancel-in-progress: true

# Tarefas (Jobs) a serem executadas
jobs:
  # Job único de deployment
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Define a URL de output do site
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do repositório
      - name: Checkout
        uses: actions/checkout@v4
      # 2. Configura o ambiente do GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      # 3. Faz o "build" do site (cria um artefato com os arquivos a serem publicados)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Publica o conteúdo da raiz do repositório
          path: '.'
      # 4. Publica o site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
  # Rodar os Testes Unitários
  test:
    # Nome do Job
    name: Run Unit Tests
    # Precisa do job de lint para passar primeiro
    needs: lint
    # Máquina virtual
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código do repositório
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Configurar o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Usando uma versão moderna do Python

      # 3. Instalar as dependências do nosso arquivo requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # 4. Rodar o Pytest!
      - name: Run tests with pytest
        run: pytest
    
  discord_notify:
  needs: deploy
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@main
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK}}
